# -*- coding: utf-8 -*-
"""Final_preprocessing_sepsis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12oNGFF-a1xKy8fYH4JNsinMbV5jWsZIx
"""

#importing libraries
from google.colab import files
from os import listdir
import pandas as pd

#uploading file (dataset in zip format) to the colab
uploaded1 = files.upload()

#unzipping the data files
!unzip training.zip

ls /content

!ls -U /content/training | head -10

#Reading psv file
data= pd.read_csv('/content/training/p01522.psv', sep='|')
data.head()

"""**Train -Validation-Test Split**"""

#Training set
traincsv = listdir('/content/training/')
with open("train.psv","wb") as fout:

  for i,csv in enumerate(traincsv):
    
    if i >=0 and i <4000:

        # first file:
      if i == 0:
        with open('/content/training/' + csv, "rb") as f:
            fout.write(f.read())
        # now the rest:    
      with open('/content/training/' + csv, "rb") as f:
        next(f) # skip the header
        fout.write(f.read())

train = pd.read_csv('/content/train.psv', sep ='|')
train.shape

train['SepsisLabel'].value_counts()

#Validation set
with open("validation.psv","wb") as fout:

  for i,csv in enumerate(traincsv):
    
    if i >=4000 and i <4500:

        # first file:
      if i == 4000:
        with open('/content/training/' + csv, "rb") as f:
            fout.write(f.read())
        # now the rest:    
      with open('/content/training/' + csv, "rb") as f:
        next(f) # skip the header
        fout.write(f.read())

validation = pd.read_csv('/content/validation.psv', sep ='|')
validation.shape

validation['SepsisLabel'].value_counts()

#Test set
with open("test.psv","wb") as fout:

  for i,csv in enumerate(traincsv):
    
    if i >=4500:

        # first file:
      if i == 4500:
        with open('/content/training/' + csv, "rb") as f:
            fout.write(f.read())
        # now the rest:    
      with open('/content/training/' + csv, "rb") as f:
        next(f) # skip the header
        fout.write(f.read())

test = pd.read_csv('/content/test.psv', sep ='|')
test.shape

test['SepsisLabel'].value_counts()

#downloading train data
files.download('train.psv')

#downloading validation data
files.download('validation.psv')

#downloading test data
files.download('test.psv')